name: ğŸ›¡ï¸ Protect Dev Branch ğŸ›¡ï¸

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  # ğŸš« Prevent Direct Pushes ğŸš« #
  prevent-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: ğŸš¨ Fail if push is made directly to dev ğŸš¨
      run: ./scripts/dev-branch-scripts/prevent_direct_push_to_dev.sh

 
  # ğŸŒ¿ Check Source Branch is Feature ğŸŒ¿ #
  check-branch-name:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ§ Check if source branch is a feature branch ğŸ§
      run: ./scripts/dev-branch-scripts/check_feature_branch.sh

