name: ğŸ“ Commit Message Length Check ğŸ“

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  # ğŸ“ Verify Commit Message Length ğŸ“ #
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“¥ Checkout code ğŸ“¥
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: ğŸ” Check Commit Length ğŸ”
      run: ./scripts/feature-branch-scripts/check_commit_length.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
