name: âœ‰ï¸ Check Commit Message âœ‰ï¸

on:
  pull_request:
    branches:
      - '*feature/*'

jobs:

  # ğŸ“œ Verify Commit Messages ğŸ“œ #
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“¥ Checkout code ğŸ“¥
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: ğŸ§ª Check commit messages ğŸ§ª
      run: ./scripts/feature-branch-scripts/check_commit_messages.sh


